export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const INCREMENT = 'INCREMENT'
export const COMBOBOX_CHANGE = 'COMBOBOX_CHANGE'
export const DATE_FROM_CHANGE = 'DATE_FROM_CHANGE'
export const DATE_TO_CHANGE = 'DATE_TO_CHANGE'
export const DATE_CHANGE = 'DATE_CHANGE'